import bcrypt from "bcryptjs";

const data = {
	users: [
		{
			name: "Basir",
			email: "admin@example.com",
			password: bcrypt.hashSync("1234", 8),
			isAdmin: true,
		},
		{
			name: "John",
			email: "user@example.com",
			password: bcrypt.hashSync("1234", 8),
			isAdmin: false,
		},
	],
	products: [
		{
			name: "Nike T-Shirt (White)",
			category: "Tshirts",
			image: "/images/p1.jpg",
			price: 89,
			countInStock: 10,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			description: "Athletic T-shirt made with quality materials",
		},
		{
			name: "Nike Short",
			category: "Short",
			image: "/images/p2.jpg",
			price: 100,
			countInStock: 20,
			brand: "Nike",
			rating: 4.0,
			numReviews: 10,
			description: "Casual short with a flame print",
		},
		{
			name: "Under Armour T-Shirt",
			category: "Tshirts",
			image: "/images/p3.jpg",
			price: 220,
			countInStock: 0,
			brand: "Under Armour",
			rating: 4.8,
			numReviews: 17,
			description: "Stylish red T-shirt",
		},
		{
			name: "Nike Air Force 1",
			category: "Shoes",
			image: "/images/p4.jpg",
			price: 78,
			countInStock: 15,
			brand: "Nike",
			rating: 4.5,
			numReviews: 14,
			description: "The kicks with the drip",
		},
		{
			name: "Adidas Slides (Black)",
			category: "Shoes",
			image: "/images/p5.jpg",
			price: 65,
			countInStock: 5,
			brand: "Adidas",
			rating: 4.5,
			numReviews: 10,
			description: "Comfortable outdoor rubber slides",
		},
		{
			name: "Nike Womens T-shirt",
			category: "Tshirts",
			image: "/images/p6.jpg",
			price: 139,
			countInStock: 12,
			brand: "Nike",
			rating: 4.5,
			numReviews: 15,
			description: "Stylish women's T-shirt",
		},
	],
};
export default data;
