const data = {
	products: [
		{
			_id: "1",
			name: "Nike T-Shirt (White)",
			category: "tshirts",
			image: "/images/p1.jpg",
			price: 89,
			countInStock: 10,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			description: "high quality product",
		},
		{
			_id: "2",
			name: "Nike Short",
			category: "Short",
			image: "/images/p2.jpg",
			price: 100,
			countInStock: 20,
			brand: "Nike",
			rating: 4.0,
			numReviews: 10,
			description: "high quality product",
		},
		{
			_id: "3",
			name: "Under Armour T-Shirt",
			category: "tshirts",
			image: "/images/p3.jpg",
			price: 220,
			countInStock: 0,
			brand: "Under Armour",
			rating: 4.8,
			numReviews: 17,
			description: "high quality product",
		},
		{
			_id: "4",
			name: "Nike Air Force 1",
			category: "shoes",
			image: "/images/p4.jpg",
			price: 78,
			countInStock: 15,
			brand: "Nike",
			rating: 4.5,
			numReviews: 14,
			description: "high quality product",
		},
		{
			_id: "5",
			name: "Adidas Slides (Black)",
			category: "shoes",
			image: "/images/p5.jpg",
			price: 65,
			countInStock: 5,
			brand: "Adidas",
			rating: 4.5,
			numReviews: 10,
			description: "high quality product",
		},
		{
			_id: "6",
			name: "Nike Womens T-shirt",
			category: "tshirts",
			image: "/images/p6.jpg",
			price: 139,
			countInStock: 12,
			brand: "Nike",
			rating: 4.5,
			numReviews: 15,
			description: "high quality product",
		},
	],
};
export default data;
